name: "Feature Request"
description: "Đề xuất tính năng mới"
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: input
    id: feature_name
    attributes:
      label: "Tên tính năng"
      placeholder: "Ví dụ: AI Test Automation"

  - type: textarea
    id: feature_description
    attributes:
      label: "Mô tả tính năng"
      placeholder: "Chi tiết cách hoạt động và lợi ích"

  - type: dropdown
    id: priority
    attributes:
      label: "Mức ưu tiên"
      options:
        - Low
        - Medium
        - High
